### ISSUE TITLE
请问作者，Event是怎么规划的，我想做点贡献，不知怎么下手

### ISSUE THREAD

**Issue by tzraeq** [gaoxiaosong/react-native-im#24]
请问作者，Event是怎么规划的，我想做点贡献，不知怎么下手。比如，群组用户加入和群组用户离开，怎样区分。目前有一个Group事件变量，按照你的规划，是不是应该[Event.Base, Event.Group, Event.MemberJoinIn]和[Event.Base, Event.Group, Event.MemberLeave]， 还是说[Event.Base, Event.GroupMemberJoinIn, xxx]和[Event.Base, Event.GroupMemberLeave, xxx]，你打算用哪种形式？我这个项目会持续一段时间，希望能够跟你保持设计思想同步。

**Comment by gaoxiaosong** [comment]
@tzraeq 我已经离职了，这个项目目前由前公司的同事维护，地址是https://github.com/hecom-rn/react-native-im

**Comment by tzraeq** [comment]
感谢！
